myapp/urls.py
from django.urls import path
from myapp.views import index,logout_view

app_name = 'myapp'

urlpatterns = [
    path('',index,name = 'index'),
    path('logout/',logout_view,name = 'logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(),name = 'login'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
import uuid


class UserType(models.Model):
	usertype = models.CharField(max_length = 50)

	def __str__(self):
		return self.usertype

class Company(models.Model):
	company = models.CharField(max_length = 50)

	def __str__(self):
		return self.company

	class Meta:
		verbose_name = 'Company'
		verbose_name_plural = 'Companies'

class State(models.Model):
	state = models.CharField(max_length = 50)

	def __str__(self):
		return self.state

class Place(models.Model):
	state = models.ForeignKey(State,on_delete = models.CASCADE)
	place = models.CharField(max_length = 50)

	def __str__(self):
		return self.place

class UserMaster(models.Model):
	user = models.ForeignKey(User,on_delete = models.CASCADE)
	full_name = models.CharField(max_length = 100)
	usertype = models.ForeignKey(UserType,on_delete = models.CASCADE)
	company = models.ForeignKey(Company,on_delete = models.CASCADE)
	#state = models.ForeignKey(State,on_delete = models.CASCADE)
	place = models.ForeignKey(Place,on_delete = models.CASCADE)
	address = models.TextField()
	email = models.EmailField()
	phone = PhoneNumberField()

	def __str__(self):
		return self.full_name

class UserInfo(models.Model):
	user = models.ForeignKey(UserMaster,on_delete = models.CASCADE)
	invoice = models.FileField(upload_to = '')
	total = models.IntegerField()
	sold = models.IntegerField(null = True,blank = True)
	remaining = models.IntegerField(null = True,blank = True)

	def __str__(self):
		return str(self.user)

myapp/forms.py
from django import forms
from myapp.models import UserInfo

class SalesForm(forms.ModelForm):
	class Meta:
		model = UserInfo
		fields = ['sold']

myapp/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from myapp.forms import SalesForm
from django.http import HttpResponseRedirect
from myapp.models import UserInfo,UserMaster
from django.contrib.auth import logout


@login_required
def index(request):
    print('im in index')
    try:
        usermaster_id = User.objects.get(id = request.user.id).id
        userinfo_id = UserMaster.objects.get(user_id = usermaster_id).id
    except:
        return render(request,'notfound.html')
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SalesForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            sold = form.cleaned_data['sold']
            u = UserInfo.objects.get(user_id = userinfo_id)
            u.sold = sold
            u.remaining = u.total - u.sold
            u.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return redirect('myapp:index')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SalesForm()

    print(usermaster_id,userinfo_id)
    if UserMaster.objects.filter(user_id = usermaster_id).exists() and UserInfo.objects.filter(user_id = userinfo_id).exists():
        
        detail = UserInfo.objects.filter(user_id = userinfo_id)
        print(detail)

        return render(request, 'index.html', {'form': form,'detail':[i for i in detail]})
    else:
        return render(request,'notfound.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('myapp:index')

myapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>DEMO</title>
	<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">@</span>
      </div>
      <input type="text" class="form-control" placeholder="{{request.user}}" aria-label="Username" aria-describedby="basic-addon1">
    </div>
  </form>
  {% if user.is_authenticated %}
  <a class = "btn btn-danger" href="{% url 'myapp:logout' %}">Logout</a>
  {% endif %}
</nav>
<div class="container">
{% block content %}
  <!-- Content here -->
{% endblock %}
</div>
</body>
</html>

myapp/templates/index.html
{% extends 'base.html' %}

{% block content %}


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">{{request.user}}</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in detail %}
    <tr>
      <th scope="row">Total</th>
      <td>{{i.total}}</td>
    </tr>
    <tr>
      <th scope="row">Invoice</th>
      <td><a href="{{i.invoice.url}}">Invoice</a></td>
    </tr>
    {% if i.sold %}
    <tr>
      <th scope="row">Sold</th>
      <td>{{i.sold}}</td>
    </tr>
    <tr>
      <th scope="row">Remaining</th>
      <td>{{i.remaining}}</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>


<br><br><br>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

myapp/templates/notfound.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>
<b>Details not found for {{request.user}}</b>
{% endblock %}